### ISSUE TITLE
Matriz de Competências

### ISSUE THREAD

**Issue by BrzGab** [unb-mds/Gastos-DF-2024-02#14]
**Descrição da Tarefa**
Coordenar a criação da Matriz de Competências da equipe, essencial para identificar habilidades e conhecimentos em tecnologias de cada membro. O objetivo é desenvolver um formulário que permita a cada membro informar suas capacidades, visando uma alocação eficiente de recursos e estratégias de capacitação.

**Objetivos**
- Identificar habilidades da equipe.
- Facilitar a alocação de recursos.
- Criar um formulário claro para coleta de informações.

**Etapas para Conclusão**
- [x] Definir áreas de conhecimento a serem abordadas.

- [x] Criar o formulário.

- [x] Coletar as respostas da equipe.

**Recursos Necessários**

1. Ferramentas para criação de formulários.

2. Exemplos de matrizes de competências.

**Relação com a Sprint**
Esta tarefa está relacionada à Sprint 0, marcando o início do projeto.

**Comment by ArtyMend07** [comment]
Formulário para a Matriz de Competências foi criado e está pronto para uso! 📝
O formulário pode ser acessado [aqui](https://docs.google.com/forms/d/e/1FAIpQLSfUV-NXA40mpgNJU0Saziyvl9DTxE_83hOWJhwQtMjBAcePeA/viewform?usp=sf_link).
