### ISSUE TITLE
Treinamento em Git e Github

### ISSUE THREAD

**Issue by BrzGab** [unb-mds/Gastos-DF-2024-02#15]
**Descrição da Tarefa**
Realizar um treinamento para a equipe sobre Git e GitHub, abordando os principais conceitos e práticas, a fim de melhorar a colaboração e o versionamento de projetos.

**Objetivos**
- Capacitar a equipe no uso de Git e GitHub.
- Melhorar a colaboração em projetos.
- Ensinar práticas de versionamento e gerenciamento de código.

**Etapas para Conclusão**

1. Preparar o conteúdo do treinamento (teoria e prática).

**Recursos Necessários**

- Material de apoio (apresentações, tutoriais, links úteis).
- Acesso a um repositório de exemplo para práticas.

**Relação com a Sprint**
Esta tarefa está relacionada à Sprint 0.

**Comment by JuliaGabP** [comment]
https://www.youtube.com/watch?v=UBAX-13g8OM&t=598s&pp=ygUPdHV0b3JpYWwgZ2l0aHVi
https://www.youtube.com/watch?v=pyM5QLS2h6M&t=1370s&pp=ygUPdHV0b3JpYWwgZ2l0aHVi
https://www.youtube.com/watch?v=Zwv9qRyVeU4&pp=ygUPdHV0b3JpYWwgZ2l0aHVi
https://www.youtube.com/watch?v=DqTITcMq68k&pp=ygUPdHV0b3JpYWwgZ2l0aHVi

**Comment by BrzGab** [comment]
https://www.youtube.com/playlist?list=PLcoYAcR89n-qbO7YAVj5S0alABLis_QVU
