### ISSUE TITLE
Criar Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by Nibaacriba** [unb-mds/Gastos-DF-2024-02#28]
**Como** designer de UX/UI ou Product Owner,  
**Quero** criar um protótipo de baixa fidelidade,  
**Para que** eu possa validar rapidamente a estrutura e a navegação do produto antes de investir em design detalhado ou desenvolvimento.

## Critérios de Aceitação:

1. **Protótipo com Estrutura Simples:**
   - O protótipo deve ser criado com ferramentas básicas, como Figma.
   - Deve ser fácil de editar e modificar conforme necessário.

2. **Cobertura das Telas Principais:**
   - Deve incluir as telas principais e fluxos essenciais do produto.
   - As telas devem refletir as principais funcionalidades e jornadas do usuário.

3. **Interações Básicas:**
   - Deve incluir indicações visuais de navegação, como botões e links, para testar o fluxo de navegação.

4. **Compreensão:**
   - O protótipo deve ser claro e fácil de entender.
   - Permitir feedback e validação inicial sobre o fluxo e a usabilidade do produto.

5. **Ajustes Iterativos:**
   - O protótipo deve permitir ajustes rápidos com base no feedback recebido.
   - Deve possibilitar adaptações conforme as revisões e necessidades identificadas.

**Comment by johnaopedro** [comment]
O Prótotipo feito com sucesso.
