### ISSUE TITLE
Treinamento em Python

### ISSUE THREAD

**Issue by johnaopedro** [unb-mds/Gastos-DF-2024-02#4]
# Descrição

Essa issue tem como objetivo a realização de um treinamento para a equipe, com foco em Python. O intuito é melhorar a proficiência da equipe em Python e garantir que todos estejam alinhados com as melhores práticas de desenvolvimento, incluindo o uso da biblioteca Flask.

# Tarefas
- [x] Pesquisar ferramentas de aprendizado.

# Critérios de Aceitação
- [x] Compilar uma lista: Criar uma lista com todos os recursos encontrados para facilitar o acesso da equipe.

**Comment by johnaopedro** [comment]
Treinamento em Python:
- https://github.com/arthurspk/guiadevbrasil
- https://www.w3schools.com/python/default.asp

Biblioteca Flask:
- https://harve.com.br/blog/programacao-python-blog/introducao-e-tutorial-ao-flask-python/
- https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

**Comment by JuliaGabP** [comment]
https://www.youtube.com/watch?v=kkoJTBtj4ds&list=PLKIusnzBtaELSrEBEnXTN07siLHmX5rm3
https://youtu.be/e9EPb5AoMf8?si=jceEiQ2pMG8MMqJB
https://solyd.com.br/cursos/python-basico/
