### ISSUE TITLE
Documentação da sprint 3

### ISSUE THREAD

**Issue by lucasarruda9** [unb-mds/Gastos-DF-2024-02#71]
# Tarefa: Criação da documentação sobre a Sprint 3

**Descrição**: Elaborar a documentação referente à Sprint 3, detalhando as atividades realizadas por cada membro da equipe.

### Detalhes

- **Responsável**: Lucas Arruda e Gabriel Lopes
- **Prazo**: 01/12/2024

### Critérios de Conclusão

- [x] A documentação deve apresentar as atividades realizadas.

**Comment by johnaopedro** [comment]
A documentação foi enviada para Review através de um Pull Request.
